import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";

import Head from "next/head";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Web3ModalProvider } from "@/context/Web3ModalContext";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cast AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={outfit.className}>
        <Web3ModalProvider>
          <Navbar />
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
